# Generated by Django 3.0.4 on 2020-03-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200318_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='rarity',
        ),
    ]
