# Generated by Django 3.0.4 on 2020-03-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_region_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='rarity',
            field=models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Epic'), ('L', 'Legendary')], default='C', max_length=1),
        ),
    ]
